apiVersion: v1
kind: Namespace
metadata:
  name: service-jhttp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhttp
spec:
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jhttp
  template:
    metadata:
      labels:
        app: jhttp
    spec:
      containers:
      - image: mshahat/harness-jhttp:latest
        name: jhttp
        ports:
        - containerPort: 8888
